### PR TITLE
Useful changes for more extensibility 

### PR DESCRIPTION
**Pull request by monajjar1**
- renamed ImageViewer.scss to build.scss
- moved all SCSS files to scss/
- introduced new variables.scss
- updated the example.html files
- introduced listeners
- introduced zoom buttons

### CODE REVIEW

**Comment by s-yadav** [comment]
Hey @monajjar1. Thanks for the PR. The changes look perfect. I wanted to check if you will be willing to maintain this library. If yes, I will add you as the core contributor with all the rights and add you on the npm to publish.

**Comment by monajjar1** [comment]
> Hey @monajjar1. Thanks for the PR. The changes look perfect. I wanted to check if you will be willing to maintain this library. If yes, I will add you as the core contributor with all the rights and add you on the npm to publish.

Got no problem with that at all

**Comment by s-yadav** [comment]
Great to know that. 🙂

**Comment by s-yadav** [comment]
I have sent you an invite. Let's connect over email if you have any questions on this.

**Comment by monajjar1** [comment]
> I have sent you an invite. Let's connect over email if you have any questions on this.

Sure thing

**Pull request merged**
