### PR TITLE
added bot initial list! 

### PR DESCRIPTION
**Pull request by grlwholifts**
added the cli tests and relevant bot commands
#61 
#59 
committed changes via @nk521 from my local machine, hope you don't mind :)

cc: @s-yadav

### CODE REVIEW

**Comment by s-yadav** [comment]
The order of contributors should be based on the number of the contribution he/she has made. Is there a way to automate that. Or it just depened on the order you add a contributor?

**Comment by grlwholifts** [comment]
hi @s-yadav the order depends on the order the contributor is added in. I haven't played around with the bot enough to know of this `based on no of contributions he/she has made`. if you know, let me know so. I will implement it :)

**Comment by grlwholifts** [comment]
hi, @s-yadav it would be great if you could review this sooner, in the review period. thanks!

**Comment by s-yadav** [comment]
Sure will do before review period only. 
We should check if things can be taken directly from github instead of manually adding this. 
There is thread
https://github.com/all-contributors/all-contributors-cli/issues/117

Also, can you look if there are any other tools for this?

**Comment by grlwholifts** [comment]
@all-contributors please add @ruchikabgosain  for adding this bot!

**Comment by grlwholifts** [comment]
> @all-contributors please add @ruchikabgosain for adding this bot!

We can add comments like this to add contributors :) @s-yadav 
we only need to manually add them the first time the bot is getting configured.

**Comment by grlwholifts** [comment]
hi @s-yadav the review period will be over today. could you please look into this?

**Pull request merged**
